-- begin TIMESHEETWITHCUBA_DATASHEET
alter table TIMESHEETWITHCUBA_DATASHEET add constraint FK_TIMESHEETWITHCUBA_DATASHEET_ON_USER foreign key (USER_ID) references TIMESHEETWITHCUBA_USER(ID)^
create index IDX_TIMESHEETWITHCUBA_DATASHEET_ON_USER on TIMESHEETWITHCUBA_DATASHEET (USER_ID)^
-- end TIMESHEETWITHCUBA_DATASHEET
-- begin TIMESHEETWITHCUBA_USER
alter table TIMESHEETWITHCUBA_USER add constraint FK_TIMESHEETWITHCUBA_USER_ON_POSITION foreign key (POSITION_ID) references TIMESHEETWITHCUBA_POSITION(ID)^
alter table TIMESHEETWITHCUBA_USER add constraint FK_TIMESHEETWITHCUBA_USER_ON_DEPARTMENT foreign key (DEPARTMENT_ID) references TIMESHEETWITHCUBA_DEPARTMENT(ID)^
create unique index IDX_TIMESHEETWITHCUBA_USER_UNIQ_NUMBER_TIMESHEET on TIMESHEETWITHCUBA_USER (NUMBER_TIMESHEET)^
create index IDX_TIMESHEETWITHCUBA_USER_ON_POSITION on TIMESHEETWITHCUBA_USER (POSITION_ID)^
create index IDX_TIMESHEETWITHCUBA_USER_ON_DEPARTMENT on TIMESHEETWITHCUBA_USER (DEPARTMENT_ID)^
-- end TIMESHEETWITHCUBA_USER
-- begin TIMESHEETWITHCUBA_DEPARTMENT
alter table TIMESHEETWITHCUBA_DEPARTMENT add constraint FK_TIMESHEETWITHCUBA_DEPARTMENT_ON_ORGANIZATION foreign key (ORGANIZATION_ID) references TIMESHEETWITHCUBA_ORGANIZATION(ID)^
create index IDX_TIMESHEETWITHCUBA_DEPARTMENT_ON_ORGANIZATION on TIMESHEETWITHCUBA_DEPARTMENT (ORGANIZATION_ID)^
-- end TIMESHEETWITHCUBA_DEPARTMENT
