alter table TIMESHEETWITHCUBA_POSITION add constraint FK_TIMESHEETWITHCUBA_POSITION_ON_BOSS foreign key (BOSS_ID) references TIMESHEETWITHCUBA_USER(ID);
create index IDX_TIMESHEETWITHCUBA_POSITION_ON_BOSS on TIMESHEETWITHCUBA_POSITION (BOSS_ID);
