exec sp_rename 'TIMESHEETWITHCUBA_POSITION.PERFORMER_ID', 'PERFORMER_ID__U80467', 'COLUMN' ^
alter table TIMESHEETWITHCUBA_POSITION drop constraint FK_TIMESHEETWITHCUBA_POSITION_ON_PERFORMER ;
drop index IDX_TIMESHEETWITHCUBA_POSITION_ON_PERFORMER on TIMESHEETWITHCUBA_POSITION ;
exec sp_rename 'TIMESHEETWITHCUBA_POSITION.BOSS_ID', 'BOSS_ID__U40872', 'COLUMN' ^
alter table TIMESHEETWITHCUBA_POSITION drop constraint FK_TIMESHEETWITHCUBA_POSITION_ON_BOSS ;
drop index IDX_TIMESHEETWITHCUBA_POSITION_ON_BOSS on TIMESHEETWITHCUBA_POSITION ;
